// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dezcoasxzuqxyaycdtba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlemNvYXN4enVxeHlheWNkdGJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIyNjU2MTAsImV4cCI6MjA0Nzg0MTYxMH0.dxqiWPvfF2q5StVDwWuP_uuAMdY1PR6_tgA44y88fuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);